---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-demo-source-git-bb-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev-demo
  secretRef:
    name: dev-demo-git-bb-app-auth
  url: ssh://git@github.com/agylpradipta/bb-app-source-event.git
